-- CW2 schema
CREATE SCHEMA CW2;
GO

-- Tables
CREATE TABLE CW2.USERS (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Firstname VARCHAR(50) NOT NULL,
    Lastname VARCHAR(50) NOT NULL,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL, -- 255 allows for hashing
    Bio VARCHAR(500) NULL,
    CityID INT NULL
);
GO

CREATE TABLE CW2.CITY (
    CityID INT IDENTITY(1,1) PRIMARY KEY,
    CityName VARCHAR(100) NOT NULL
);
GO

CREATE TABLE CW2.ACTIVITY (
    ActivityID INT IDENTITY(1,1) PRIMARY KEY,
    ActivityName VARCHAR(100) NOT NULL
);
GO

CREATE TABLE CW2.USERACTIVITY ( --Linking table
    UserID INT NOT NULL,
    ActivityID INT NOT NULL,
    PRIMARY KEY (UserID, ActivityID)
);
GO

-- Foreign keys
ALTER TABLE CW2.USERS -- USERS to CITY
ADD CONSTRAINT FK_Users_City
FOREIGN KEY (CityID) REFERENCES CW2.CITY(CityID);
GO

ALTER TABLE CW2.USERACTIVITY --USERACTIVITY to USERS and ACTIVITY
ADD CONSTRAINT FK_UserActivity_User
FOREIGN KEY (UserID) REFERENCES CW2.USERS (UserID);
GO

ALTER TABLE CW2.USERACTIVITY
ADD CONSTRAINT FK_UserActivity_Activity
FOREIGN KEY (ActivityID) REFERENCES CW2.ACTIVITY (ActivityID);
GO