IF OBJECT_ID('CW2.USERACTIVITY', 'U') IS NOT NULL
BEGIN
    ALTER TABLE CW2.USERACTIVITY DROP CONSTRAINT IF EXISTS FK_UserActivity_User;
    ALTER TABLE CW2.USERACTIVITY DROP CONSTRAINT IF EXISTS FK_UserActivity_Activity;
END
GO

IF OBJECT_ID('CW2.USERS', 'U') IS NOT NULL
BEGIN
    ALTER TABLE CW2.USERS DROP CONSTRAINT IF EXISTS FK_Users_City;
END
GO

DROP TABLE IF EXISTS CW2.USERACTIVITY;
DROP TABLE IF EXISTS CW2.USERS;
DROP TABLE IF EXISTS CW2.ACTIVITY;
DROP TABLE IF EXISTS CW2.CITY;
GO